### PR TITLE
Remove jQuery Dependency

### PR DESCRIPTION
**Pull request by zackbloom**
@fiatjaf I ended up removing the jQuery dependency.  You can try my version here: https://eager.io/app/ITqbuiF6hdq1/install?initialUrl=https%3A%2F%2Fwww.reddit.com%2F&options=%7B%22container%22%3A%22%23siteTable%22%2C%22next%22%3A%22a%5Brel%3D%5C%22nofollow%20next%5C%22%5D%22%7D&version=v1.2.5-rc3

It's very cool! As you can see, it loads one page, then runs into an unrelated issue.

For your information, I also fixed the jQuery issue here: https://github.com/fiatjaf/eager-infinitescroll/commit/62f4bdb1d641b075522643614f4b5263125bc2f7.  The jQuery project changed the location of jquery.js at some point between version 1.7.0 and the present day, making it necessary to change the path, and be more restrictive in the versioning.  Additionally, you were using `$` in the file, but using `jQuery` in the install.json file.

Thanks for doing all of this, we really appreciate it, and can't wait for the app to be live.

### CODE REVIEW

**Comment by fiatjaf** [comment]
First I tried to search for a small javascript library that done everything for me (and should be battle-tested and better than what I could come up with), but I've only found old things, and all them requiring jQuery. Then I tried to write it myself without jQuery. That failed, because there uncompatibilities between Chrome and Firefox (at least) on the values of `document.body.scrollHeight` and `document.body.scrollTop` (the solution possible should involve detecting something about the rendering engine and using alternatively `document.body` and `document.documentElement`). If you tested in Firefox and haven't run into these issues then I'm dead wrong and I don't understand how could that be (since I run into them, and they were magically solved by introduction of jQuery).

**Comment by fiatjaf** [comment]
I can't do it now, but I'll try this version later and see if I can fix the other issue you ran into.

**Comment by zackbloom** [comment]
@fiatjaf I see, if you can reproduce the scroll issue and happen to know the versions of FF and Chrome where you saw it we're happy to take a pass at coming up with something compatible with both browsers.

**Comment by fiatjaf** [comment]
I fixed the problem that was happening in Reddit (due to poorly thought HTML structure, Reddit "next" links were being added to the DOM and so being removed from `tmp`), but the non-jQuery version, although working in Chrome, does not work in my Firefox here. Besides my experience, there are quotes around the internet stating the incompatibility I have previously spoken about, so I think it is real. It is probably solvable, and I tried a little, but couldn't get my head all over the problem.

So I have taken your fix of my `install.json`, but not the removal of jQuery.

**Pull request closed without merging**
